<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ip-172-31-76-77" name="dataDriven.Guru99Project" tests="3" failures="1" timestamp="2020-10-29T04:28:34 UTC" time="18.141" errors="0">
  <testcase name="loginToApplication" time="6.472" classname="dataDriven.Guru99Project"/>
  <system-out/>
  <testcase name="loginToApplication" time="5.863" classname="dataDriven.Guru99Project">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Guru99 Bank Manager HomePage] but found [Guru99 Bank Home Page],
	expected [http://demo.guru99.com/v4/manager/Managerhomepage.php] but found [http://demo.guru99.com/v4/]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Guru99 Bank Manager HomePage] but found [Guru99 Bank Home Page],
expected [http://demo.guru99.com/v4/manager/Managerhomepage.php] but found [http://demo.guru99.com/v4/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at dataDriven.Guru99Project.loginToApplication(Guru99Project.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- loginToApplication -->
  <system-out/>
  <testcase name="loginToApplication" time="5.806" classname="dataDriven.Guru99Project"/>
  <system-out/>
</testsuite> <!-- dataDriven.Guru99Project -->
